name: Build job
on:
  push:
    branches: main
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout spring boot project repo
        uses: actions/checkout@v2
      - name: Build spring boot project with Maven
        run: mvn clean install -DskipTests
      - name: Create directory on Desktop
        run: mkdir $HOME\Desktop\myapp
      - name: Copy JAR to Desktop
        run: |
          copy target\firstproject-0.0.1-SNAPSHOT.jar $HOME\Desktop\myapp\
      
