name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      MY_SECRET: ${{ secrets.YOUR_SECRET_NAME }}

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout spring boot project repo
        uses: actions/checkout@v2

      - name: Create secrets.properties
        run: echo "my-secret-property=${{ secrets.YOUR_SECRET_NAME }}" > src/main/resources/secrets.properties

      - name: Build spring boot project with Maven
        run: |
          mvn clean install -DskipTests
          mkdir -p ./spring-boot-project/artifacts
          cp target/*.jar ./spring-boot-project/artifacts/

      - name: List files in artifacts directory
        run: |
          dir ./spring-boot-project/artifacts

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-artifact
          path: ./spring-boot-project/artifacts
